[package]
name = "Liquidswap"
version = "0.2.7"

[addresses]
liquidswap = "0x2d7ae95e4f067836b540771b95531ea87f8f30dfd6c1667c496875f1ba65738f"
dao_admin = "0xb4d7b2466d211c1f4629e8340bb1a9e75e7f8fb38cc145c54c5c9f9d5017a318"
emergency_admin = "0xb4d7b2466d211c1f4629e8340bb1a9e75e7f8fb38cc145c54c5c9f9d5017a318"

# Addresses for tests.
test_coin_admin = "0x11"
test_helpers = "0x12"

test_lp_owner = "0x12"
test_pool_addr = "0x98c053307e6f9bc3d3fb35768b08ea6c530187bf7b43fd0326ea59b9c9f9ef7d"

[dependencies.LPCoin]
local = "./lp_coin/"

[dependencies.LPInit]
local = "./lp_init/"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "8f634bcd2e48c4972868d0053d3532f4f760ae19"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.UQ64x64]
git = "https://github.com/pontem-network/UQ64x64.git"
rev = "v0.3.6"

[dependencies.U256]
git = "https://github.com/pontem-network/U256.git"
rev = "v0.3.6"
