[package]
name = 'LPCoin'
version = '1.0.0'

[addresses]
lp_coin_account = "0x35e1873b2a1ae8c609598114c527b57d31ff5274f646ea3ff6ecad86c56d2cf8"

[dev-dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "8f634bcd2e48c4972868d0053d3532f4f760ae19"
subdir = "aptos-move/framework/move-stdlib"
