[package]
name = 'FlashloanTest'
version = '1.0.0'

[addresses]
flashloan_test = "0x43417434fd869edee76cca2a4d2301e528a1551b1d719b75c350c3c97d15b8b9"

[dependencies.Liquidswap]
local = "../"

[dependencies.TestCoins]
local = "../../test-coins"
